custom_envs:
  MetamathQA:
    env_type: metamathqa
    max_actions_per_traj: 5
    env_instruction: "You are solving Math problems. "
    max_tokens: 100
    env_config: null

  MetamathQA_1Turn:
    env_type: metamathqa
    max_actions_per_traj: 1
    env_instruction: "You are solving Math problems. "
    max_tokens: 100
    env_config: null

  MetamathQA_2Turn:
    env_type: metamathqa
    max_actions_per_traj: 2
    env_instruction: "You are solving Math problems. "
    max_tokens: 100
    env_config: null

  MetamathQA_4Turn:
    env_type: metamathqa
    max_actions_per_traj: 4
    env_instruction: "You are solving Math problems. "
    max_tokens: 100
    env_config: null

  MetamathQA_6Turn:
    env_type: metamathqa
    max_actions_per_traj: 6
    env_instruction: "You are solving Math problems. "
    max_tokens: 100
    env_config: null

  MetamathQA_8Turn:
    env_type: metamathqa
    max_actions_per_traj: 8
    env_instruction: "You are solving Math problems. "
    max_tokens: 100
    env_config: null

  MetamathQA_10Turn:
    env_type: metamathqa
    max_actions_per_traj: 10
    env_instruction: "You are solving Math problems. "
    max_tokens: 100
    env_config: null

