defaults:
  - ppo_trainer
  - envs

system:
  CUDA_VISIBLE_DEVICES: "0"

micro_batch_size_per_gpu: 1
ppo_mini_batch_size: 8
model_path: Qwen/Qwen2.5-32B-Instruct
enable_response_mask: True
grpo_advantage_length_weight: False

lora:
  enabled: False
  rank: 64
  alpha: 64
  target_modules: all-linear
  local_temp_dir: lora_temp

# 启用模型量化
quantization:
  enabled: True
  bits: 4  # 4位量化，大幅减少显存需求

actor_rollout_ref:
  model:
    path: ${model_path}
    quantization:
      enabled: ${quantization.enabled}
      bits: ${quantization.bits}
  actor:
    strategy: 'fsdp'
    ppo_mini_batch_size: ${ppo_mini_batch_size}
    micro_batch_size_per_gpu: ${micro_batch_size_per_gpu}
    ppo_micro_batch_size_per_gpu: ${micro_batch_size_per_gpu}
    use_ref: False
    entropy_coeff: 0.001
    use_kl_loss: False
    kl_loss_coef: 0.001
    kl_loss_type: kl
    clip_ratio_low: 0.2
    clip_ratio_high: 0.28
    grpo_advantage_length_weight: ${grpo_advantage_length_weight}
    optim:
      betas: [0.9, 0.999]
    lora:
      enabled: ${lora.enabled}
      rank: ${lora.rank}
      alpha: ${lora.alpha}
      target_modules: ${lora.target_modules}
      local_temp_dir: ${lora.local_temp_dir}
  ref:
    log_prob_micro_batch_size_per_gpu: ${micro_batch_size_per_gpu}
  rollout:
    log_prob_micro_batch_size_per_gpu: ${micro_batch_size_per_gpu}
    tensor_model_parallel_size: 1
    max_model_len: 3600
    prompt_length: 1
    response_length: 400
    gpu_memory_utilization: 0.95
    max_num_batched_tokens: 4096
    enforce_eager: True
    free_cache_engine: True
    val_kwargs:
      do_sample: False
      temperature: 0
    lora:
      enabled: ${lora.enabled}
      rank: ${lora.rank}
      alpha: ${lora.alpha}
      target_modules: ${lora.target_modules}
      local_temp_dir: ${lora.local_temp_dir}

critic:
  strategy: 'fsdp'
  ppo_mini_batch_size: ${ppo_mini_batch_size}
  ppo_micro_batch_size_per_gpu: ${micro_batch_size_per_gpu}
  model:
    path: ${model_path}
  optim:
    betas: [0.9, 0.999]
  lora:
    enabled: ${lora.enabled}
    rank: ${lora.rank}
    alpha: ${lora.alpha}
    target_modules: ${lora.target_modules}

data:
  max_prompt_length: null
  max_response_length: null
  train_batch_size: null

algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: gae
  kl_penalty: kl
  kl_ctrl:
    type: fixed
    kl_coef: 0.001

trainer:
  project_name: ragen_appendix
  experiment_name: qwen_metamathqa_eval
  total_training_steps: 0
  validation_steps: 1
  val_before_train: True
  n_gpus_per_node: 1
  test_freq: 10
  generations_to_log_to_wandb: 
    train: 0
    val: 20
  logger: [ 'console', 'wandb' ]

agent_proxy:
  max_turn: 5
  action_sep: "||"
  max_actions_per_turn: 5
  use_turn_scores: False
  enable_think: True
  reward_normalization:
    grouping: "state"
    method: "identity"

val_agent_proxy:
  max_turn: 5

es_manager:
  format_penalty: -0.1
  train:
    env_groups: 0
    group_size: 0
    env_configs:
      tags: ["MetamathQA"]
      n_groups: [0]
  val:
    env_groups: 128
    group_size: 1
    env_configs:
      tags: ["MetamathQA"]
      n_groups: [128]

ctx_manager:
  generation:
    gen_config:
      response_length: ${actor_rollout_ref.rollout.response_length}
      temperature: ${actor_rollout_ref.rollout.temperature}
      top_p: ${actor_rollout_ref.rollout.top_p}
      top_k: ${actor_rollout_ref.rollout.top_k}
      kwargs: null 